---
kind: pipeline
type: docker
name: build

steps:
- name: Build
  image: ubuntu:22.04
  commands:
  - ./scripts/setup-debian.sh
  - ansible-lint ./play_all.yml
  - ansible-galaxy install -r ./requirements.yml
  - ansible-playbook play_developer.yml -i inv_localhost --extra-vars="pubkey='ssh-rsa PubKey'"
