name: Test checkov

on:
  workflow_dispatch:

jobs:
  terraform-security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3.0.2

      - name: Checkov security scan
        uses: bridgecrewio/checkov-action@v12.1347.0
        with:
          framework: terraform
          output_format: cli
          quiet: true
          soft_fail: false