name: Test checkov

on:
  workflow_dispatch:

jobs:
  terraform-security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3.1.0

      - name: Checkov security scan
        uses: bridgecrewio/checkov-action@v12.1347.0
        with:
          framework: terraform
          output_format: cli
          quiet: true
          soft_fail: false